{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure_basic.py:9: AssertionError"}, "description": "this test fails", "start": 1592303807672, "stop": 1592303807672, "uuid": "3cef6aa1-e5d6-45c6-9197-23da2876598e", "historyId": "5ba089da54bf162df7c1b20e64f45144", "testCaseId": "1a95f24ee76f491c77e33d898a1df9a7", "fullName": "test_allure_basic#test_failure", "labels": [{"name": "suite", "value": "test_allure_basic"}, {"name": "host", "value": "LAPTOP-4F3KR3S3"}, {"name": "thread", "value": "13920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_basic"}]}